config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'static_pages#top'

  resources :users
  resource :profile

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :boards, shallow: true do
    resources :comments, only: %i[create destroy]
    resource :bookmarks, only: [:create, :destroy]
    collection do
      get :bookmarks
    end
  end
  resources :password_resets, only: %i[new create edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  mount_uploader :board_image, BoardImageUploader

  validates :title, length: { maximum: 255 }, presence: true
  validates :body, length: { maximum: 65535 }, presence: true

  scope :bookmarked_by, -> user {
    joins(:bookmarks).where('bookmark.user_id = ?', user_id)
  }

end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :board

  validates :user_id, uniqueness: { scope: :board_id}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :board

  validates :body, length: { maximum: 65535 }, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  # お気に入りにしている掲示板を取得する
  has_many :bookmarks_boards, through: :bookmarks, source: :board

  mount_uploader :avatar, AvatarUploader

  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, uniqueness: true, allow_nil: true

  validates :email, uniqueness: true, presence: true

  validates :last_name, presence: true, length: { maximum: 255}
  validates :first_name, presence: true, length: { maximum: 255}

  # オブジェクトがユーザー自身のものか判断する
  def own?(object)
    object.user_id == id
  end

  # お気に入り追加
  # <<で引数で渡した掲示板の情報がbookmark_boardsに入っている
  def bookmark(board)
    bookmarks_boards << board
  end

  # お気に入りを外す
  def unbookmark(board)
    bookmarks_boards.delete(board)
  end

  # お気に入り登録しているか判定するメソッド
  def bookmark?(board)
    bookmarks_boards.include?(board)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

private

  def not_authenticated
    redirect_to login_path, alert: 'ログインしてください'
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
before_action :set_board, only: [:show, :edit, :update, :destroy]
  def index
    @search = Board.ransack(params[:q])
    @boards = @search.result(distinct: true).all.includes([:user, :bookmarks]).order(created_at: :desc).page(params[:page])
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.create(board_params)
    if @board.save
      redirect_to boards_path, success: '掲示板作成しました'
    else
      flash.now[:danger] = '掲示板作成に失敗しました'
      render :new
    end
  end

  def show
    @comments = @board.comments.all.order(created_at: :desc)
    @comment = Comment.new
  end

  def edit; end

  def update
    if @board.update(board_params)
      redirect_to board_path(@board), success: '掲示板を更新しました'
    else
      render :edit
      flash[:danger] = '掲示板を更新できませんでした'
    end
  end

  def destroy
    @board.destroy!
    redirect_to boards_path, success: '掲示板を削除しました'
  end

  def bookmarks
    @search = current_user.bookmarks_boards.ransack(params[:q])
    @bookmark_boards = @search.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

private

  def board_params
    params.require(:board).permit(:title, :body, :board_image, :board_image_cache)
  end

  def set_board
    @board = current_user.boards.find(params[:id])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController


  def create
    @board = Board.find(params[:board_id])
    current_user.bookmark(@board)
    # redirect_back fallback_location: root_path, success: 'ブックマークしました'
  end

  def destroy
    @board = current_user.bookmarks.find_by(params[:id]).board
    current_user.unbookmark(@board)
    # redirect_back fallback_location: root_path, success: 'ブックマークを外しました'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = current_user.comments.create(comment_params)
    if comment.save
      redirect_to board_path(comment.board), success: 'コメントを投稿しました'
    else
      redirect_to board_path(comment.board)
      flash.now[:danger] = 'コメントの投稿に失敗しました'
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to board_path(comment.board), success: 'コメントを削除しました'
  end

private

  def comment_params
    params.require(:comment).permit(:body).merge(board_id: params[:board_id])
  end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_action :require_login

  def new; end

  def create
    binding.pry
    @user = User.find_by(email: params[:email])
    @user&.deliver_reset_password_instructions!
    redirect_to(root_path, :notice => 'メールを送信しました')
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end

    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.change_password(params[:user][:password])
      redirect_to(root_path, :notice => 'Password was successfully updated.')
    else
      render :edit
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to profile_path, success: 'プロフィールを更新しました'
    else
      render :edit
      flash[:danger] = 'プロフィールを更新できませんでした'
    end
  end

private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :email, :password, :password_confirmation, :avatar, :avatar_cache)
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      flash[:success] = 'ログインに成功しました'
      redirect_to boards_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    logout
    flash[:success] = 'ログアウトしました'
    redirect_to root_path
  end

private

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザー登録が完了しました。'
      redirect_to login_path
    else
      flash.now[:danger] = 'ユーザー登録に失敗しました'
      render :new
    end
  end

private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = 'RUNTEQ BOARD APP'

    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end
end

app/views/boards/_board.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="board-id-<%=board.id%>">
    <div class="card">
      <%= image_tag board.board_image.url, class: 'card-img-top', width: 300, height: 200 %>
        <div class="card-body">
          <h4 class="card-title">
            <%= link_to "#{ board.title }", board_path(board) %>
          </h4>
          <div class='mr10 float-right'>
            <% if current_user.own?(board) %>
              <div class='mr10 float-right'>
              <%= render 'crud_menus', board: board %>
            <% else %>
              <%= render 'boards/bookmark_area', board: board %>
              </div>
            <% end %>
          </div>
          <ul class="list-inline">
            <li class="list-inline-item"><i class="far fa-user"></i> <%= board.user.decorate.full_name %></li>
            <li class="list-inline-item"><i class="far fa-calendar"></i><%= l board.created_at, format: :short %></li>
          </ul>
          <p class="card-text"><%= board.body%></p>
        </div>
    </div>
  </div>
</div>

app/views/boards/_bookmark.html.erb
<%= link_to board_bookmarks_path(board_id: board.id),
        id: "js-bookmark-button-for-board-#{board.id}",
        method: :post,
        remote: true do %>
  <%= icon 'far', 'star' %>
<% end%>

app/views/boards/_bookmark_area.html.erb
<% if current_user.bookmark?(board) %>
  <%= render 'boards/unbookmark', board: board %>
<% else %>
  <%= render 'boards/bookmark', board: board %>
<% end %>

app/views/boards/_crud_menus.html.erb
<%= link_to edit_board_path(board), id: 'button-edit-#{board.id}' do %>
  <%= icon 'fa', 'pen' %>
<% end %>
<%= link_to board_path(board), id: 'button-delete-#{board.id}', method: :delete, data: {confirm: '削除しますか？'} do %>
  <%= icon 'fas', 'trash' %>
<% end %>

app/views/boards/_form.html.erb
<%= form_with model: @board, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control mb-3' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control mb-3' %>
  </div>

  <div class="form-group">
    <%= f.label :board_image %>
    <%= f.file_field :board_image, onchange: 'previewImage()', class: 'form-control mb-3', accept: 'image/*' %>
    <%= f.hidden_field :board_image_cache %>
  </div>
  <div class="mt-3 mb-3">
    <%= image_tag board.board_image.url,
                      class: 'rounded-ciecle',
                      id: 'preview',
                      size: '100x100' %>

  </div>

  <%= f.submit class: 'btn btn-primary'%>
<% end %>

<script>
function previewImage() {
  const target = this.event.target;
  const file = target.files[0];
  const reader = new FileReader();
  reader.onloadend = function () {
    const preview = document.querySelector("#preview")
    if(preview) {
      preview.src = reader.result;
    }
  }
  if (file) {
    reader.readAsDataURL(file);
  }
}
</script>

app/views/boards/_search_form.html.erb
<%= search_form_for search, url: url do |f| %>
  <div class="input-group mb-3"><%= f.search_field :title_or_body_cont, class: "form-control", placeholder: '検索ワード' %></div>
  <div class="input-group-append"><%= f.submit "検索", class: "btn btn-primary" %></div>
<% end%>

app/views/boards/_unbookmark.html.erb
<%= link_to board_bookmarks_path(current_user.bookmarks.find_by(board_id: board.id)),
              id: "js-bookmark-button-for-board-#{board.id}", 
              method: :delete, 
              remote: true do %>
  <%= icon 'fas', 'star' %>
<% end %>

app/views/boards/bookmarks.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
       <%= render 'search_form', search: @search, url: bookmarks_boards_path %>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="row">
      <% if @bookmark_boards.present? %>
        <%= render partial: "board", collection: @bookmark_boards %>
      <% else %>
        <p>ブックマーク中の掲示板がありません</p>
      <% end%>
      </div>
    </div>
    <%= paginate @bookmark_boards %>
  </div>
</div>

app/views/boards/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
   <div class="row">
     <div class="col-lg-8 offset-lg-2">
        <h1><%= t('.title') %></h1>
        <%= render 'form', { board: @board } %>
     </div>
  </div>
</div>

app/views/boards/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <%= render 'search_form', search: @search, url: boards_path %>
    </div>
  </div>
  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
      <% if @boards.present?%>
        <%= render @boards %>
      <% else %>
        <p>掲示板がありません</p>
      <% end%>
      </div>
    </div>
    <%= paginate @boards %>
  </div>
</div>

app/views/boards/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
   <div class="row">
     <div class="col-lg-8 offset-lg-2">
        <h1>掲示板作成</h1>
        <%= render 'form', { board: @board } %>
     </div>
  </div>
</div>

app/views/boards/show.html.erb
<% content_for(:title, @board.title) %>
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <h1>掲示板詳細</h1>
      <!-- 掲示板内容 -->
      <article class="card">
        <div class="card-body">
          <div class='row'>
            <div class='col-md-3'>
              <%= image_tag @board.board_image.url, class: "card-img-top img-fluid", width: 300, height: 200 %>
            </div>
            <div class='col-md-9'>
              <h3 style='display: inline;'><%= @board.title %></h3>
              <ul class="list-inline">
                <li class="list-inline-item">by <%= @board.user.decorate.full_name %></li>
                <li class="list-inline-item"><%= l @board.created_at, format: :short %></li>
              </ul>
            </div>
          </div>
          <p><%= @board.body %></p>
          <% if current_user.own?(@board) %>
            <div class='mr10 float-right'>
              <%= link_to edit_board_path(@board), id: 'button-edit-#{board.id}' do %>
                <%= icon 'fa', 'pen' %>
              <% end %>
              <%= link_to board_path(@board), id: 'button-delete-#{board.id}', method: :delete, data: {confirm: '削除してもいいですか？'} do %>
                <%= icon 'fas', 'trash' %>
              <% end %>
            </div>
          <% end %>
        </div>
      </article>
    </div>
  </div>

  <!-- コメントフォーム -->
  <%= render 'comments/form', {board: @board, comment: @comment} %>

  <!-- コメントエリア -->
  <% if @comments.present? %>
    <%= render @comments %>
  <% end %>
</div>

app/views/bookmarks/create.js.erb
$("#js-bookmark-button-for-board-<%= @board.id %>").html("<%= j(render('boards/unbookmark', board: @board)) %>");

app/views/bookmarks/destroy.js.erb
$("#js-bookmark-button-for-board-<%= @board.id %>").html("<%= j(render('boards/bookmark', board: @board)) %>");

app/views/comments/_comment.html.erb
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <table id="js-table-comment" class="table">
        <tr id="comment-#{comment.id}">
          <td style="width: 60px">
            <%= image_tag comment.user.avatar_url, width: 50, height: 50, class: "rounded-circle" %>
          </td>
          <td>
            <h3 class="small"><%= comment.user.decorate.full_name %></h3>
            <div id="js-comment-25">
              <p><%= comment.body %></p>
            </div>
            <div style="display: none;">
              <textarea class="form-control mb-1"><%= comment.body %></textarea>
              <button class="btn btn-light">キャンセル</button>
              <button class="btn btn-success">更新</button>
            </div>
          </td>

          <td class="action">
            <ul class="list-inline justify-content-center" style="float: right;">
              <li class="list-inline-item">
                <a href="#"><i class='fa fa-pencil'></i></a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-trash"></i>
                </a>
              </li>
            </ul>
          </td>
        </tr>
      </table>
    </div>
  </div>

app/views/comments/_form.html.erb
<div class="row mb-3">
  <div class="col-lg-8 offset-lg-2">
    <%= form_with model: comment, url: [board, comment], local: true do |f|%>
    <%= render 'shared/error_messages', object: f.object %>
      <%= f.text_field :body, class: 'form-control mb-3', placeholder: 'コメント' %>

      <%= f.submit '投稿', class: 'btn btn-primary' %>

    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
    <%= render 'shared/header' %>
    <% else %>
    <%= render 'shared/before_login_header' %>
    <% end%>
    <%= render 'shared/flash_message'%>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/password_resets/create.html.erb
<h1>PasswordResets#create</h1>
<p>Find me in app/views/password_resets/create.html.erb</p>

app/views/password_resets/edit.html.erb
<h1>Choose a new password</h1>
<%= form_for @user, :url => password_reset_path(@token), :html => {:method => :put} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="field">
    <%= f.label :email %><br />
    <%= @user.email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Password?</h1>
<%= form_with url: password_resets_path, local: true do |form| %>
  <div class="field">
    <%= form.label :email %><br />
    <%= form.text_field :email %>
    <%= form.submit "Reset my password!" %>
  </div>
<% end %>

app/views/password_resets/update.html.erb
<h1>PasswordResets#update</h1>
<p>Find me in app/views/password_resets/update.html.erb</p>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>プロフィール編集</h1>
      
      <%= form_with model: @user, url: profile_path, method: :patch, local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control" %>
        </div>
        <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "form-control" %>
        </div>
        <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :avatar %>
          <%= f.file_field :avatar, onchange: 'previewImage()', class: 'form-control mb-3', accept: 'image/*' %>
          <%= f.hidden_field :avatar_cache %>
        </div>
        <div class="mt-3 mb-3">
          <%= image_tag @user.avatar.url,
                            class: 'rounded-ciecle',
                            id: 'preview',
                            size: '100x100' %>

        </div>
        <%= f.submit "登録", class: "btn btn-primary" %>
      <% end %>
      <div class='text-center'>
        <%= link_to "ログインページへ", login_path %>
      </div>
    </div>
  </div>
</div>


<script>
function previewImage() {
  const target = this.event.target;
  const file = target.files[0];
  const reader = new FileReader();
  reader.onloadend = function () {
    const preview = document.querySelector("#preview")
    if(preview) {
      preview.src = reader.result;
    }
  }
  if (file) {
    reader.readAsDataURL(file);
  }
}
</script>

app/views/profiles/show.html.erb
<% content_for(:title, t('.title')) %>
 <div class="container pt-3">
   <div class="row">
     <div class="col-md-10 offset-md-1">
       <h1 class="float-left mb-5"><%= t('.title') %></h1>
       <%= link_to t('defaults.edit'), edit_profile_path, class: 'btn btn-success float-right' %>
       <table class="table">
         <tr>
           <th scope="row"><%= t(User.human_attribute_name(:email)) %></th>
           <td><%= current_user.email %></td>
         </tr>
         <tr>
           <th scope="row"><%= t(User.human_attribute_name(:full_name)) %></th>
           <td><%= current_user.decorate.full_name %></td>
         </tr>
         <tr>
           <th scope="row"><%= t(User.human_attribute_name(:avatar)) %></th>
           <td><%= image_tag current_user.avatar.url, class: 'rounded-circle', size: '50x50' %></td>
         </tr>
       </table>
     </div>
   </div>
 </div>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'logo.png'%>
    <% end %>
    
    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to 'ログイン', login_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-6 col-12'>
        <div class='copyright'>
          <p>Copyright © 2019. RUNTEQ</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <a class='navbar-brand' href='/'>
      <%= image_tag 'logo.png'%>
    </a>
    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ml-auto main-nav align-items-center'>
        <li class='nav-item dropdown dropdown-slide'>
          <a href='#' class='nav-link dropdown-toggle' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
            掲示板
          </a>

          <div class='dropdown-menu dropdown-menu-right'>
          <%= link_to '掲示板一覧', boards_path, class: 'dropdown-item' %>
          <%= link_to '掲示板作成', new_board_path, class: 'dropdown-item' %>
          </div>
        </li>

        <li class='nav-item'>
          <%= link_to 'ブックマーク一覧', bookmarks_boards_path, class: 'nav-link' %>
        </li>

        <li class='nav-item dropdown dropdown-slide'>
          <a href='#' class='nav-link' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false' id='header-profile'>
            <%= image_tag current_user.avatar.url, class: 'rounded-circle mr15', width: 40, height: 40 %>
          </a>
          <div class='dropdown-menu dropdown-menu-right'>
            <div class='dropdown-item'><%= current_user.decorate.full_name %></div>
            <div class='dropdown-divider'></div>
            <%= link_to 'プロフィール', profile_path, class: 'dropdown-item' %>
            <%= link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item'%>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/static_pages/top.html.erb
<div class='top-wrapper'>
  <div class='top-inner-text'>
    <h1>RUNTEQ BOARD APP</h1>
  </div>
</div>

app/views/user_sessions/_form.html.erb
<%= form_with url: login_path, method: :post, local: true do |f| %>
  <%#= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :email, User.human_attribute_name(:email) %>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :password, User.human_attribute_name(:password) %>
    <%= f.password_field :password,  class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Login", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<% content_for(:title, 'ログインページ') %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>ログイン画面</h1>
      <%= render 'form' %>
      <%= link_to '登録ページへ', new_user_path %><br/>
      <%= link_to 'パスワードをお忘れの方はこちら', new_password_reset_path %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>ユーザー登録</h1>
      
      <%= form_with model: @user, local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control" %>
        </div>
        <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "form-control" %>
        </div>
        <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        <%= f.submit "登録", class: "btn btn-primary" %>
      <% end %>
      <div class='text-center'>
        <%= link_to "ログインページへ", login_path %>
      </div>
    </div>
  </div>
</div>